apiVersion: v1
kind: Pod
metadata:
  name: ece271b-jupyter
  labels:
    app: ece271b
    task: jupyter
spec:
  restartPolicy: Never
  containers:
  - name: jupyter-container
    image: ghcr.io/kkuntal990/seed-mining:latest
    imagePullPolicy: Always
    command: ["/bin/bash", "-c"]
    args:
      - |
        cd /app &&
        jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=selfimprove

    resources:
      limits:
        nvidia.com/rtxa6000: "1"
        memory: "32Gi"
        cpu: "4"
      requests:
        nvidia.com/rtxa6000: "1"
        memory: "32Gi"
        cpu: "4"

    volumeMounts:
      - name: cache-volume
        mountPath: /cache
      - name: output
        mountPath: /output
      - name: dev-shm
        mountPath: /dev/shm

    env:
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-token
          key: token
          optional: true
    - name: HF_HOME
      value: "/cache/hf"
    - name: TRANSFORMERS_CACHE
      value: "/cache/hf/transformers"
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: PYTORCH_CUDA_ALLOC_CONF
      value: "expandable_segments:True"

  tolerations:
    - effect: NoSchedule
      key: nautilus.io/hardware
      operator: Equal
      value: large-gpu
    - effect: PreferNoSchedule
      key: nvidia.com/gpu
      operator: Exists
    - key: nautilus.io/reservation
      operator: Exists
      effect: NoSchedule
    - key: nautilus.io/issue
      operator: Exists
      effect: NoSchedule

  volumes:
    - name: output
      persistentVolumeClaim:
        claimName: seed-mining-output
    - name: cache-volume
      emptyDir:
        sizeLimit: 100Gi
    - name: dev-shm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
